### ISSUE TITLE
[UI] includes social icons under users' card on about me page

### ISSUE THREAD

**Issue by wajeht** [closed-carrot/website#32]
## User story
As a user, I want to see the professional credentials of a user

### Description
- Add social media icons under users' cards on the about me page
- Make it match the branch color
- Make it responsive

#### Note
- use https://react-icons.github.io/react-icons/ for icons
- see `src/views/components/Users.jsx` for how to use icons

**Comment by krshinn** [comment]
Completed and pushed to feature branch.  Also got updates from McCall, Netty, and Mark on Core Values, and updated those to suggested changes
